### ISSUE TITLE
Webpack build does not move Images or Textures

### ISSUE THREAD

**Issue by BGR360** [maxdow/cesiumjs-webpack-boilerplate#1]
Hi maxdow,

I'm very new to Webpack, but not to Cesium. I did everything according to your specification in the README, but when I open the webpage I get this:

![screen shot 2016-08-01 at 12 28 07 pm](https://cloud.githubusercontent.com/assets/13339928/17301120/71470eca-57e3-11e6-873b-bf0e6750ef9f.png)

Is there any way to make Webpack copy over the contents of the `cesium/Source/Widgets/Images` and `cesium/Source/Assets` directories into the `./public` directory?

**Comment by maxdow** [comment]
Hi. 

I found a build error with last node version. I fixed it by upgrading dependencies but i can't reproduce the bug. 

Can you upgrade and tell me if it is still wrong ?

**Comment by daumann** [comment]
I have the same issue. Can you be more specific than "upgrading dependencies" - which dependencies and to what version?

Are you referring to this commit? 
https://github.com/maxdow/cesiumjs-webpack-boilerplate/commit/e88a50ecddbed740656120d7eef49b0d154058d5

That does not fix it for me. Which version of node/ npm are you using?

**Comment by maxdow** [comment]
Yes, i had a webpack build error (path must be string). I solved it by upgrading loaders. I am using node 6.3.0.

I will investigate more

**Comment by maxdow** [comment]
@daumann @BGR360 what OS are you using ?

**Comment by daumann** [comment]
@maxdow Ubuntu 14.04

Maybe are you forgetting a step like this: https://github.com/mmacaula/cesium-webpack/blob/master/using-source/postinstall.sh ?

**Comment by maxdow** [comment]
thanks , yes I can reproduce it , i work on the fix ;)

**Comment by daumann** [comment]
@maxdow  cool and thanks for the repo!

**Comment by maxdow** [comment]
should work now

**Comment by daumann** [comment]
can confirm, it works now
