### ISSUE TITLE
webpack2 error

### ISSUE THREAD

**Issue by xujinghai** [maxdow/cesiumjs-webpack-boilerplate#4]
Thanks maxdow, It is really fantasy! I’m a beginner in webpack and try to move your project to angular 2 cli and get webpack.config.js through ng eject.  And I notice the angular 2 use Webpack 2. So I upgrade the webpack and webpack-dev to
     
 "webpack": "^2.2.0 ",
 "webpack-dev-server": "~2.4.2"

in your project. Current  pacage.json file is:

{
  "name": "cesium-webpack-boilerplate",
  "version": "1.1.0",
  "description": "A boilerplate for cesiumjs",
  "main": "app.js",
  "scripts": {
    "clean": "mkdirp public & rimraf public/*",
    "build": "npm run clean && cpr node_modules/cesium/Build/Cesium public && webpack --config config/webpack.config.js --progress",
    "devserver": "webpack-dev-server --config config/webpack.config.js --progress --watch",
    "dev": "npm run build && npm run devserver",
    "release": "npm run build -- --optimize-minimize"
  },
  "author": "Maxime Warnier",
  "license": "MIT",
  "dependencies": {
    "cesium": "^1.19.0"
  },
  "devDependencies": {
    "cpr": "^1.1.2",
    "css-loader": "^0.23.1",
    "file-loader": "^0.9.0",
    "html-webpack-plugin": "^2.22.0",
    "mkdirp": "^0.5.1",
    "rimraf": "^2.5.2",
    "script-loader": "^0.7.0",
    "style-loader": "^0.13.0",

    "webpack": "^2.2.0 ",
    "webpack-dev-server": "~2.4.2"
  }
}

Current Webpack.config.js is 

var HtmlPlugin = require("html-webpack-plugin");
const path = require('path');
module.exports = {
    entry: "./src/app.js",
    output: {
        path: path.join(process.cwd(), "public"),
        filename: "bundle.js",
        sourcePrefix: ""
    },
    plugins: [
        new HtmlPlugin({
            template: "./src/index.html",
            inject: "body"
        })
    ],
    devServer: {
        contentBase: path.join(process.cwd(), "public")
    },
    module: {
        unknownContextCritical: false,
        loaders: [
            { test: /\.css$/, loader: "style-loader!css-loader" },
            {
                test: /\.(png|gif|jpg|jpeg)$/,
                loader: "file-loader"
            },
            { test: /Cesium\.js$/, loader: "script-loader" }
        ]
    }
};

But I get errors, when I debug the project.

Error constructing CesiumWidget.
Visit <a href="http://get.webgl.org">http://get.webgl.org</a> to verify that your web browser and hardware support WebGL.  Consider trying a different web browser or updating your video drivers.  Detailed error information is below:
Error: Cannot find module "."
Error: Cannot find module "."
    at webpackMissingModule (http://localhost:8080/vendor.bundle.js:31564:69)
    at buildModuleUrl (http://localhost:8080/vendor.bundle.js:31564:147)
    at new Globe (http://localhost:8080/vendor.bundle.js:187847:34)
    at new CesiumWidget (http://localhost:8080/vendor.bundle.js:228862:25)
    at new Viewer (http://localhost:8080/vendor.bundle.js:234446:28)
    at Object.358 (http://localhost:8080/main.bundle.js:59:14)
    at __webpack_require__ (http://localhost:8080/inline.bundle.js:55:30)
    at Object.876 (http://localhost:8080/main.bundle.js:195:18)
    at __webpack_require__ (http://localhost:8080/inline.bundle.js:55:30)
    at webpackJsonpCallback (http://localhost:8080/inline.bundle.js:26:23)
  CesiumWidget.showErrorPanel	
  CesiumWidget	
  Viewer	
  358	
  __webpack_require__	
  876	
  __webpack_require__	
  webpackJsonpCallback	
  (anonymous function)	
Uncaught Error: Cannot find module "."
  webpackMissingModule	
  buildModuleUrl	
  Globe	
  CesiumWidget	
  Viewer	
  358	
  __webpack_require__	
  876	
  __webpack_require__	
  webpackJsonpCallback	
  (anonymous function)	
Angular is running in the development mode. Call enableProdMode() to enable the production mode.

**Comment by maxdow** [comment]
Hi. Thanks for your message.

I have to update the webpack version. Maybe to V3 since webpack 3 has been released ( and there is no changes with 2 for this kind of configuration).

About your problem, it not seems to be related with webpack. The error message is from Cesium, so , ~Cesiumjs is correctly bundled~.

I got this error on a project i am working on. It is working in a computer and in other one, i got this message. This could come from the browser or the video driver configuration. 

Try to go to http://get.webgl.org  to see if webgl is enabled

**Comment by maxdow** [comment]
Ok i've just tested and i got the same error. I will fix this

**Comment by maxdow** [comment]
I released a V2. Major points are 
- Migration to webpack 3
- Use of a separate lib folder to load Cesium

Can you try this ?

**Comment by xujinghai** [comment]
Thanks maxdow. Your new version of the boilerplate is correct now and works well. Great job!

However when I move it to the angular 2 cli webpack.config.js, I get warning info…

WARNING in ./node_modules/raw-loader!./node_modules/source-map-loader!./lib/CesiumUnminified/Cesium.js
(Emitted value instead of an instance of Error) Cannot find SourceMap 'protobuf.js.map': Error: Can't resolve './protobuf.js.map' in 'C:\Users\xjh\WebstormProjects\AngularCesium\lib\CesiumUnminified'
 @ ./lib/CesiumUnminified/Cesium.js 1:104-373
 @ ./src/app.js
 @ multi ./src/main.ts ./src/app.js
Child html-webpack-plugin for "index.html":
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 385 bytes {0} [built]

Then the project can start but get display map incorrect. I guess the problems are located in the webpack.config.js.

What I did just create a new Angular 2 cli project through webstorm wizard and use ng eject to get the default webpack.config.js of the project and then merge your webpack configure info to the project’s webpack.config.js with an arbitrary way by directly copy and add the scripts. 

The project files locate: https://github.com/xujinghai/AngularCesium.git


Would you please help to fix these problems?

**Comment by maxdow** [comment]
Hi,

there is no sourcemap generation with this boilerplate. You could try to set devtool option in webpack.config.js to generate sourcemaps : https://webpack.js.org/configuration/devtool/

**Comment by maxdow** [comment]
I will close this issue because the initial problem is fixed. Feel free to open a new one if you still have pb with sourcemaps
